/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class WhereItem (
  /* You can explain the controls of more than one state with where. The controls of states: equal, notEqual, like, greaterThan, lessThan */
  `type`: Option[String],
  /* Column name */
  column: Option[String],
  /* Column value */
  value: Option[String]
) extends ApiModel


